-- supabase/migrations/YYYYMMDDHHMMSS_create_bank_transactions_table.sql

CREATE TABLE IF NOT EXISTS public.bank_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    analysis_id BIGINT REFERENCES public.saved_analyses(id),
    transaction_type TEXT NOT NULL, -- 'bet', 'win', 'loss_refund', 'cancellation_refund', 'deposit', 'withdrawal'
    amount BIGINT NOT NULL, -- Valor em centavos para evitar problemas de precisão
    initial_bank_balance BIGINT NOT NULL, -- Saldo da banca *antes* da transação (em centavos)
    final_bank_balance BIGINT NOT NULL, -- Saldo da banca *depois* da transação (em centavos)
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON COLUMN public.bank_transactions.amount IS 'Valor da transação em centavos';
COMMENT ON COLUMN public.bank_transactions.initial_bank_balance IS 'Saldo da banca antes da transação, em centavos';
COMMENT ON COLUMN public.bank_transactions.final_bank_balance IS 'Saldo da banca depois da transação, em centavos';
