-- GoalScan: ledger atômico alinhado ao schema atual (bank_settings.id TEXT, saved_analyses.id TEXT, total_bank NUMERIC).
-- Remove tabela legada incompatível (centavos/user_id), se existir.
DROP FUNCTION IF EXISTS public.update_bet_and_bank_transactional(UUID, BIGINT, TEXT, BIGINT, NUMERIC);

DROP TABLE IF EXISTS public.bank_transactions CASCADE;

CREATE TABLE public.bank_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bet_id TEXT NOT NULL REFERENCES public.saved_analyses (id) ON DELETE CASCADE,
  amount NUMERIC(15, 2) NOT NULL CHECK (amount >= 0),
  type TEXT NOT NULL CHECK (type IN ('DEBIT', 'CREDIT', 'PROFIT')),
  balance_after NUMERIC(15, 2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_bank_transactions_bet_id ON public.bank_transactions (bet_id);
CREATE INDEX idx_bank_transactions_created_at ON public.bank_transactions (created_at DESC);

COMMENT ON TABLE public.bank_transactions IS 'Histórico atômico de movimentos de banca por aposta (DEBIT stake, CREDIT reembolso, PROFIT ganho líquido/retorno conforme operação).';
COMMENT ON COLUMN public.bank_transactions.amount IS 'Valor absoluto do movimento (sempre >= 0).';
COMMENT ON COLUMN public.bank_transactions.type IS 'DEBIT reduz banca; CREDIT e PROFIT aumentam (classificação de auditoria).';

ALTER TABLE public.bank_transactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous access" ON public.bank_transactions;
CREATE POLICY "Allow anonymous access" ON public.bank_transactions FOR ALL USING (true) WITH CHECK (true);

-- Transação atômica: bloqueia bank_settings, valida saldo, atualiza banca, registra ledger, persiste bet_info.
-- p_signed_delta: alteração em total_bank (negativo = saída, positivo = entrada).
-- p_increment_leverage_day: incrementa leverageProgressionDay no JSON ao marcar ganho (progressão).
CREATE OR REPLACE FUNCTION public.process_bet_transaction (
  p_settings_id TEXT,
  p_bet_id TEXT,
  p_signed_delta NUMERIC,
  p_tx_type TEXT,
  p_tx_amount NUMERIC,
  p_bet_info JSONB,
  p_increment_leverage_day BOOLEAN DEFAULT FALSE
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.bank_settings%ROWTYPE;
  v_current NUMERIC(15, 2);
  v_new NUMERIC(15, 2);
  v_final_bet JSONB;
  v_day INT;
  v_updated INT;
BEGIN
  IF p_settings_id IS NULL OR p_bet_id IS NULL THEN
    RAISE EXCEPTION 'settings_id e bet_id são obrigatórios';
  END IF;

  IF p_tx_type IS NULL OR p_tx_type NOT IN ('DEBIT', 'CREDIT', 'PROFIT') THEN
    RAISE EXCEPTION 'Tipo de transação inválido: %', p_tx_type;
  END IF;

  SELECT * INTO v_row FROM public.bank_settings WHERE id = p_settings_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'bank_settings não encontrado: %', p_settings_id;
  END IF;

  v_current := COALESCE(v_row.total_bank, 0);

  IF COALESCE(p_signed_delta, 0) IS DISTINCT FROM 0 THEN
    IF p_tx_amount IS NULL OR p_tx_amount < 0 THEN
      RAISE EXCEPTION 'p_tx_amount deve ser >= 0 quando há movimento de saldo';
    END IF;

    v_new := v_current + p_signed_delta;

    IF v_new < 0 THEN
      RAISE EXCEPTION 'Saldo insuficiente (saldo %, delta %)', v_current, p_signed_delta;
    END IF;

    IF p_tx_type = 'DEBIT' AND p_signed_delta < 0 THEN
      IF v_current + p_signed_delta < 0 THEN
        RAISE EXCEPTION 'Saldo insuficiente para débito';
      END IF;
    END IF;

    UPDATE public.bank_settings
    SET
      total_bank = v_new,
      updated_at = (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT
    WHERE id = p_settings_id;

    INSERT INTO public.bank_transactions (bet_id, amount, type, balance_after)
    VALUES (p_bet_id, p_tx_amount, p_tx_type, v_new);
  ELSE
    v_new := v_current;
  END IF;

  v_final_bet := p_bet_info;
  IF COALESCE(p_increment_leverage_day, FALSE) THEN
    v_day := COALESCE((p_bet_info->>'leverageProgressionDay')::INT, 0);
    v_final_bet := jsonb_set(
      p_bet_info,
      '{leverageProgressionDay}',
      to_jsonb(v_day + 1),
      TRUE
    );
  END IF;

  UPDATE public.saved_analyses
  SET
    bet_info = v_final_bet,
    updated_at = NOW()
  WHERE id = p_bet_id;

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  IF v_updated = 0 THEN
    RAISE EXCEPTION 'saved_analyses não encontrado: %', p_bet_id;
  END IF;

  RETURN jsonb_build_object(
    'success', TRUE,
    'balance_after', v_new,
    'signed_delta', p_signed_delta,
    'bet_info', v_final_bet
  );
END;
$$;

REVOKE ALL ON FUNCTION public.process_bet_transaction (TEXT, TEXT, NUMERIC, TEXT, NUMERIC, JSONB, BOOLEAN) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.process_bet_transaction (TEXT, TEXT, NUMERIC, TEXT, NUMERIC, JSONB, BOOLEAN) TO anon;
GRANT EXECUTE ON FUNCTION public.process_bet_transaction (TEXT, TEXT, NUMERIC, TEXT, NUMERIC, JSONB, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.process_bet_transaction (TEXT, TEXT, NUMERIC, TEXT, NUMERIC, JSONB, BOOLEAN) TO service_role;
